### PR TITLE
tpyos

### PR DESCRIPTION
**Pull request by Deathamns**

### CODE REVIEW

**Comment by niden** [comment]
Merging this because it is great work. Just for the future, the API docs are auto created from the Zephir/Phalcon source code. All these typos exist in the docblocks in Phalcon's source :/

Note to self: do not update the api docs without a diff..

**Comment by niden** [comment]
Thank you @Deathamns

**Comment by Deathamns** [comment]
I've kind of missed the last sentence in the **Changes to English documents** section...

But finding them was the hard part, and now I know where they are. I could fix them there as well.

Also, my other PR (#2645) doesn't make sense, so I closed it.

**Comment by ruudboon** [comment]
@Deathamns If you have time and could drop a pull to the 4.0.x branch on the Phalcon repo for these files it would be great!

**Pull request merged**
