### PR TITLE
Added the last polish translation to the tutorial file

### PR DESCRIPTION
**Pull request by PolDeveloper**
Added the last polish translation to the tutorial file, with Jurigaga's valueable comments.

### CODE REVIEW

**Comment by sergeyklay** [comment]
@Jurigag Could you please take a look

**Comment by sergeyklay** [comment]
Thank you

**Comment by PolDeveloper** [comment]
Cheers!

**Comment by Jurigag** [comment]
@PolDeveloper https://crowdin.com/project/phalcon-documentation just you know we will switch here for translating new doucumentation(Refactor branch here)

**Comment by PolDeveloper** [comment]
@Jurigag Good to know, Thanks

**Pull request merged**
