### PR TITLE
renamed phalcon\mvc\url to phalcon\url

### PR DESCRIPTION
**Pull request by ekmst**
https://github.com/phalcon/cphalcon/pull/13831

### CODE REVIEW

**Comment by ekmst** [comment]
@niden done

**Comment by niden** [comment]
Ack. We don't translate translations. Only English. Crowdin handles the rest of it :/

Can you revert the languages other than English please?

**Comment by niden** [comment]
And as for #2152 I will need to review the content for v4 before that is fixed, so that can wait a bit.

**Comment by ekmst** [comment]
> Ack. We don't translate translations. Only English. Crowdin handles the rest of it :/
> 
> Can you revert the languages other than English please?

I'm sorry.
I'll do it now

**Comment by ekmst** [comment]
@niden fixed

**Comment by niden** [comment]
Thank you @ekmst

**Pull request merged**
