### PR TITLE
adding route model conversor example

### PR DESCRIPTION
**Pull request by mattvb91**

### CODE REVIEW

**Comment by andresgutierrez** [comment]
Could you please change it to `return Product::findFirstById($id);` ?

**Comment by mattvb91** [comment]
:+1:  Updated to findFirstById.

**Comment by andresgutierrez** [comment]
Thanks

**Comment by sergeyklay** [comment]
@SidRoberts Can you please apply this to other languages?

**Comment by SidRoberts** [comment]
Added other languages in https://github.com/phalcon/docs/commit/c315ad3e96429ab48de58f0c685a6cb24659a9b7 :)

**Comment by sergeyklay** [comment]
:+1:

**Pull request merged**
