### PR TITLE
Adding Reference Docs for ResourceAware, RoleAware and function based access in ACL

### PR DESCRIPTION
**Pull request by Jurigag**
There is commit with this feature: https://github.com/phalcon/cphalcon/commit/577219c94c960a5ecdae1447912fdd46a9c645fc

Tell me if it's fine, maybe i should change something or write something more about this features, then i will add polish reference to it's ok.

### CODE REVIEW

**Comment by Jurigag** [comment]
@SidRoberts

**Comment by SidRoberts** [comment]
Whoops, I was waiting for https://github.com/phalcon/cphalcon/pull/11306 to be merged and I've just realised it's the wrong PR. :stuck_out_tongue:

**Comment by Jurigag** [comment]
Well you read it ? I will later add docs in polish when i have time.

**Comment by SidRoberts** [comment]
Actually, having read the code blocks again, I'd suggest renaming the classes to `UserRole` and `ModelResource` to make it clearer. I've also noticed that the `$userID` property in Model isn't actually set anywhere. Other than that, it looks good.

**Comment by Jurigag** [comment]
OH that needs to be fixed :D

**Pull request merged**
