### PR TITLE
fix description of filter "slashes" in volt docs (the PHP function is…

### PR DESCRIPTION
**Pull request by marvasDE**
… addslashes instead of slashes)

Fix all languages. Only russian was correct.

### CODE REVIEW

**Comment by niden** [comment]
@marvasDE Thank you for this contribution. We don't merge things into the master branch directly we use the relevant branches for that.

Would you be so kind as to issue the PR to the `3.1.x` branch?

Thanks!

**Comment by marvasDE** [comment]
Now I changed the branch, but it's not only my commit now because master is ahead. 
Is this okay or should I cherry pick my commit?

**Comment by Jurigag** [comment]
You should rebase.

**Comment by sergeyklay** [comment]
@marvasDE Нужно либо сделать ребейз, чтоб в твоем пулл реквесте остались только твои коммиты, либо закрыть этот пулл реквест и открыть новый.

**Comment by marvasDE** [comment]
https://github.com/phalcon/docs/pull/984

**Pull request closed without merging**
