### PR TITLE
Add script to update RST files and fix generate-trstrings.php bug

### PR DESCRIPTION
**Pull request by kenjis**
A system to update RST files.

With this we can update translated documentation using transifex `<lang>.json` files.

Real example: https://phalcon-docs-ja.herokuapp.com/index.html

### CODE REVIEW

**Comment by niden** [comment]
Thank you @kenjis. We will briefly put this on hold since we have not finished working on the automated documentation yet. Once 2.0 is out we will address this.

Thanks again

**Comment by kenjis** [comment]
How about this?

**Comment by sergeyklay** [comment]
@SidRoberts

**Comment by SidRoberts** [comment]
We've decided to get rid of Transifex (see #717 for details) so this PR is no longer needed. Apologies it took so long to decide and thank you very much for contribution. :)

**Pull request closed without merging**
