### PR TITLE
Replaced and updated notSave event 

### PR DESCRIPTION
**Pull request by butamuh4o**
Please make review of this. i think this in documentation is mistake. Check it (notSave or notSaved). 
Thank u

### CODE REVIEW

**Comment by andresgutierrez** [comment]
Hello, I've removed notSave in 2.0.4 just leaving notSaved

**Comment by butamuh4o** [comment]
Cool. In that case this doc fix its on time. Thank you!

**Comment by butamuh4o** [comment]
Its a small changes... is it some problem with that commit?

**Comment by andresgutierrez** [comment]
Thanks

**Pull request merged**
