### PR TITLE
Bug fix in Model validate example

### PR DESCRIPTION
**Pull request by pauliuspetronis**
[https://forum.phalconphp.com/discussion/7419/compatible-with-phalconmvcmodelvalidatorinterface](https://forum.phalconphp.com/discussion/7419/compatible-with-phalconmvcmodelvalidatorinterface)

### CODE REVIEW

**Comment by sergeyklay** [comment]
@pauliuspetronis this changes works only with 2.0.4 - 2.0.5 but documentation about all 2.x series. Can you please fix this in you commit?

**Comment by sergeyklay** [comment]
@carvajaldiazeduar

**Comment by pauliuspetronis** [comment]
@sergeyklay, ok i can fix. But then I will need to split example in 2 blocks:
```php
//before 2.0.4
public function validate(ModelInterface record) {}

// from 2.0.4
public function validate(EntityInterface record){}
```
Or any other way exist? I don't find information about documentation writing rules :)

**Comment by sergeyklay** [comment]
there is nothing wrong, just add a note (or comment)

**Comment by pauliuspetronis** [comment]
I added note (only EN). #613

**Pull request merged**
