### PR TITLE
Docs translations pl

### PR DESCRIPTION
**Pull request by PolDeveloper**
Another portion of translation into polish version of tutorial

### CODE REVIEW

**Comment by sergeyklay** [comment]
@Jurigag Could you please take a look

**Comment by sergeyklay** [comment]
@PolDeveloper, @Jurigag 

Also we have a project on Transifex. The purpose of this project is to translate the Phalcon web site
https://www.transifex.com/phalcon/phalcon/phalcon-website/

**Comment by sergeyklay** [comment]
Thanks

**Comment by PolDeveloper** [comment]
Thanks for merging.
I have just sent a request to join Phalcon team on transifex.
Would be gr8 to be part of this team.
Cheers!

**Pull request merged**
