### PR TITLE
Update models.rst

### PR DESCRIPTION
**Pull request by uonick**
fix

### CODE REVIEW

**Comment by niden** [comment]
@xboston :)

**Comment by uonick** [comment]
@xboston :+1:

**Comment by andresgutierrez** [comment]
@sergeyklay

**Comment by sergeyklay** [comment]
@andresgutierrez @niden All right

**Comment by sergeyklay** [comment]
@uonick Thanks

**Comment by uonick** [comment]
No. Thank you! :smile:

**Pull request merged**
