### PR TITLE
Update webserver-setup.md

### PR DESCRIPTION
**Pull request by armanism24**
Added NGINX installation tutorial

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
cc @niden

**Comment by niden** [comment]
Sorry we do not link to other blogs resulting to traffic increase from our sites to the target one. If you want to offer a change that links to official sites or sites of our sponsors such as Digital Ocean please do.

**Comment by armanism24** [comment]
Sorry for that @niden , but there is no other tutorial available for ubuntu's latest version.
I just wanted to improve this doc with the latest guide.
No problem, if you don't want to link any third-party website's guide.

**Comment by niden** [comment]
I don;t know how latest this version is of Ubuntu but here is one that you can use:

https://www.digitalocean.com/community/tutorials/how-to-install-nginx-on-ubuntu-20-04

**Comment by armanism24** [comment]
This is not based on Ubuntu 21.04.

**Comment by armanism24** [comment]
Also, that guide ( i added in "webserver-setup.md" ) helps users to build NGINX from the source.

**Pull request closed without merging**
