### PR TITLE
Change release notes link direct to cphalcon version of 3.2

### LINKED ISSUE #1171: Remove the Changelog from the docs
I propose to remove the Changelog from the docs.

* It is unlikely that someone will translate it
* It will change constantly in the original repo, even older versions (formatting, links to issues, etc)
* We already duplicate it in two places - GitHub Release Page and Blog Posts

Cc: @phalcon/documentation

### PR DESCRIPTION
**Pull request by ninjapanzer**
Closes #1171 

Doesn't fully remove them. But uses the one in phalcon/cphalcon instead.

Does that sound ok @sergeyklay?

### CODE REVIEW

**Review by sergeyklay — APPROVED** [review]
Cc: @niden

**Comment by sergeyklay** [comment]
@ninjapanzer What about 3.1 and 4.0 branches?

**Comment by ninjapanzer** [comment]
Heck I didn't even know about the 4.0 branch. Yep I will take care of it this morning

**Comment by ninjapanzer** [comment]
@sergeyklay Please see
#1177 (`3.1`) and #1176 (`4.0`) for the same changes across their respective branches

**Comment by niden** [comment]
Thank you!

**Pull request merged**
