### PR TITLE
Corrected grammar error

### PR DESCRIPTION
**Pull request by quasipickle**
Simplified the sentence as well.

### CODE REVIEW

**Comment by niden** [comment]
@quasipickle Do you mind sending this also to 3.3? Thanks!!

**Comment by quasipickle** [comment]
Can I do this from this commit or do I have to make a new one?

**Comment by niden** [comment]
@quasipickle I think you will need to create a new PR for that. (sorry for the late reply)

**Comment by sergeyklay** [comment]
@quasipickle ping

**Comment by niden** [comment]
Thank you!

**Pull request merged**
