### PR TITLE
updated acl

### PR DESCRIPTION
**Pull request by emiliodeg**
fixed var name

### CODE REVIEW

**Comment by niden** [comment]
Thank you!

**Comment by tempcke** [comment]
@niden I'm not yet sure why but the update seemed to have not rendered as expected: 
image

may want to revert or correct this.  sorry

**Comment by tempcke** [comment]
Maybe there needs to be a newline after line 484 here: https://github.com/phalcon/docs/commit/94eb0f335215b7d715fb889f55d4155a1b4d6ab0#diff-ff5a423ebed6ffcf4cb9e8bd07908923R484

**Comment by tempcke** [comment]
Just realized I'm putting these comments on the wrong PR .. but anyway, now you know

**Comment by emiliodeg** [comment]
In the documentation in [English](https://docs.phalconphp.com/en/3.4/acl#roles-inheritance) it looks bad, but in [Spanish](https://docs.phalconphp.com/es/3.4/acl#roles-inheritance) it don't

**Comment by tempcke** [comment]
I created an issue for this here: https://github.com/phalcon/docs/issues/1950

**Pull request merged**
