### PR TITLE
All the urls are badly formed

### PR DESCRIPTION
**Pull request by emiliodeg**
added support for version and language in all urls
Apply to the rest of the languages?

### CODE REVIEW

**Comment by ninjapanzer** [comment]
Good catch! Thank You!

I took a look through the history and it seems this file in all languages has always been lacking the correct languages.

**Comment by ninjapanzer** [comment]
As I think about this some more it is a nice simplification if this `index.md` was copied to the other languages since there is no real translation impact.

@niden do we only need to make this change to the `en` version and crowding will propagate the change to the rest of the languages?

**Comment by niden** [comment]
Yes this should go to the `en` copy so that crowdin can handle it. @emiliodeg can we close this and issue it to the `/en/api/index.md` please?

**Comment by emiliodeg** [comment]
Yes of course, do what you have to do

**Comment by emiliodeg** [comment]
Another problem is that every API file has all the references of objects in the parameters of the methods has the same problem with the urls
It is also repeated in the header with the definitions of implementation and extension

**Comment by ninjapanzer** [comment]
Let me take a look at this some more I might be able to solve some of this at the markdown parser.

**Comment by niden** [comment]
This has been implemented in the `en` language and will propagate to the rest through crowdin.

Thanks @emiliodeg

**Pull request closed without merging**
