### PR TITLE
change dir ="rtl

### PR DESCRIPTION
**Pull request by javadrajabi**
my language is rtl .So it should be left to right content

### CODE REVIEW

**Comment by SidRoberts** [comment]
Is this better?:

```html
<html lang="fa" dir="rtl">
```

**Comment by javadrajabi** [comment]
Excuse my English is poor.
How do I access my Html tags? Examples in which branch?

**Comment by SidRoberts** [comment]
It's OK, I can understand you. :)

The `<html>` tag is here: [fa/_theme/phalcon/layout.html (line 111)](https://github.com/phalcon/docs/blob/master/fa/_theme/phalcon/layout.html#L111)

Make changes in either 3.0.0 or master - I'll copy the changes to the other branch.

**Comment by javadrajabi** [comment]
If I change my whole  html document.
Latin text go right and (;)  The beginning of the text;
Part of the text should be right to left
This is bad view.
Please see the photos.
What is the remedy?

**Comment by javadrajabi** [comment]
blue Line its way
red line is incorrect
green line is red line is correct

**Comment by sergeyklay** [comment]
Thank you

**Pull request merged**
